# Kamal deploy configuration for Static site service
service: <%= ENV['PROJECT_NAME'] %>-app

# NOTE: this must match the name you passed to the container registry module
# Container image
image: <%= ENV['DOCKER_HUB_USERNAME'] %>/<%= ENV['PROJECT_NAME'] %>-app

# Deploy to these servers
servers:
  web:
    - "<%= ENV['SERVER_IP'].strip %>"

# SSH configuration
ssh:
  user: root
  keys: ["<%= ENV['SSH_PRIVATE_KEY_FILE'] %>"]

# Registry configuration for Docker Hub
registry:
  username: <%= ENV['DOCKER_HUB_USERNAME'] %>
  password:
    - DOCKER_HUB_TOKEN

# Builder configuration
builder:
  dockerfile: app/Dockerfile
  context: "."
  arch: amd64
  cache:
    type: registry

# Proxy configuration for SSL
proxy:
  ssl: true
  host: <%= ENV['HOST_NAME'] %>
  app_port: 8080
  healthcheck:
    path: /
